{"author":{"id":"849e56d06e3336f74000df728dce87c471f475652db43122ead01451da9830c9"},"ops":[{"type":1,"timestamp":1584219143,"metadata":{"github-id":"MDU6SXNzdWU1ODEzNjc3MDY=","github-url":"https://github.com/MichaelMure/git-bug/issues/356","origin":"github"},"nonce":"MmZccfyQaYs2jKwXEo2SOidDW8w=","title":"git-bug and git-ssb validation","message":"Big git-bug fan here. ‚ù§\n\nI was just testing git-bug together with [git-ssb](https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256), and need to look into this further, to see what is causing what appears to be a git bug push write error. [1]\n\nNote that regular pushes, git-ssb with `git push [ssb|origin] branch` are working fine.\n\n[1]: $ git bug push ssb\n```\n        if (err) throw err\n                 ^\nError: write EPIPE\n    at afterWriteDispatched (internal/stream_base_commons.js:154:25)\n    at writeGeneric (internal/stream_base_commons.js:145:3)\n    at Socket._writeGeneric (net.js:786:11)\n    at Socket._write (net.js:798:8)\n    at doWrite (_stream_writable.js:392:12)\n    at writeOrBuffer (_stream_writable.js:374:5)\n    at Socket.Writable.write (_stream_writable.js:314:12)\n    at /usr/local/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:61:18\n    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-git-remote-helper/index.js:469:11\n    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-git-remote-helper/lib/pkt-line.js:31:9 {\n  errno: -32,\n  code: 'EPIPE',\n  syscall: 'write'\n}\n\nerror: failed to push some refs to 'ssb://%R264c0DkGTUTmdUbcl844IL0KD6kPP7QGUpsnF0EfAY=.sha256'\n```","files":null}]}